version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task_manager
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - task_network

networks:
  task_network:
    driver: bridge
