version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task_manager
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - task_network
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    networks:
      - task_network
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:

networks:
  task_network:
    driver: bridge
